# This is a basic workflow to help you get started with Actions

name: testing out

on:
  push:
    branches: [main]

jobs:
  install-build:
    outputs:
      job-strategy-matrix: ${{ steps.install.outputs.job-strategy-matrix }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install
        id: install
        run: |
          echo pnpm install
          node ./gen-service-version.js

  build-services:
    needs: [install-build]
    runs-on: ubuntu-latest
    if: ${{ needs.install-build.outputs.job-strategy-matrix != '[]' }}
    strategy:
      matrix:
        service: ${{ needs.install-build.outputs.job-strategy-matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        run: |
          ./${{ matrix.service }}/build.sh
