# This is a basic workflow to help you get started with Actions

name: testing out

on:
  push:
    branches: [ main ]

jobs:
  job1:
    outputs:
      uwu: ${{ steps.fun.outputs.uwu }}
    runs-on: ubuntu-latest

    steps:
      - name: echo owo
        id: fun
        run: | 
          echo owo
          $output=owo
  job2:
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
      - name: Echo other output
        run: test owo = ${{ needs.job1.outputs.uwu }}
