# This is a basic workflow to help you get started with Actions

name: testing out

on:
  push:
    branches: [ main ]

jobs:
  install-build:
    outputs:
      foo-service: 'false'
      bar-service: 'true'
    runs-on: ubuntu-latest
    steps:
      - name: install
        id: install
        run: | 
          echo pnpm install

  foo-service:
    needs: [install-build]
    runs-on: ubuntu-latest
    if: needs.install-build.outputs.foo-service
    steps:
      - name: Build
        run: |
          echo "building..." ${{ needs.install-build.outputs.foo-service }}

  bar-service:
    needs: [install-build]
    runs-on: ubuntu-latest
    if: "${{ needs.install-build.outputs.bar-service }}"
    steps:
      - name: Build
        run: |
          echo "building ..." ${{ needs.install-build.outputs.bar-service }}
